In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [13]:
# load the dataset
df = pd.read_csv('Untitled Folder/earthquake_alert_balanced_dataset.csv')

In [14]:
df.head()

   magnitude  depth  cdi  mmi   sig  alert
0        7.0   14.0  8.0  7.0   0.0  green
1        6.9   25.0  4.0  4.0 -33.0  green
2        7.0  579.0  3.0  3.0 -13.0  green
3        7.3   37.0  5.0  5.0  65.0  green
4        6.6  624.0  0.0  2.0 -98.0  green

In [15]:
df.describe()

         magnitude        depth          cdi          mmi          sig
count  1300.000000  1300.000000  1300.000000  1300.000000  1300.000000
mean      7.061008    50.321538     6.976154     6.939231    -9.749231
std       0.423738   104.348286     2.244875     1.354774    62.245214
min       6.500000     2.000000     0.000000     1.000000  -128.000000
25%       6.700000    12.000000     6.000000     6.000000   -54.000000
50%       7.000000    19.000000     8.000000     7.000000    -7.000000
75%       7.300000    38.000000     8.000000     8.000000    31.000000
max       8.600000   670.000000     9.000000     9.000000   127.000000

In [16]:
df.columns

Index(['magnitude', 'depth', 'cdi', 'mmi', 'sig', 'alert'], dtype='object')

In [17]:
x = df[df.columns[:-1]]

In [18]:
y = df[df.columns[-1]]

In [56]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=22)

In [57]:
knn_model = KNeighborsClassifier()
nb_model = GaussianNB()
svm_model = SVC()

In [58]:
knn_model.fit(x_train,y_train)
nb_model.fit(x_train,y_train)
svm_model.fit(x_train,y_train)

SVC()

In [59]:
knn_pred = knn_model.predict(x_test)
nb_pred = nb_model.predict(x_test)
svm_pred = svm_model.predict(x_test)

In [60]:
print(classification_report(y_test,knn_pred))

              precision    recall  f1-score   support

       green       0.85      0.62      0.72        71
      orange       0.80      0.87      0.83        68
         red       0.83      0.93      0.87        56
      yellow       0.76      0.83      0.79        65

    accuracy                           0.80       260
   macro avg       0.81      0.81      0.80       260
weighted avg       0.81      0.80      0.80       260

In [97]:
nb_x_train,nb_x_test,nb_y_train,nb_y_test = train_test_split(x,y,test_size=0.2,random_state=100)
nb_model.fit(nb_x_train,nb_y_train)
nbx_pred = nb_model.predict(nb_x_test)
print(classification_report(y_test,nb_pred))

              precision    recall  f1-score   support

       green       0.89      0.69      0.78        71
      orange       0.64      0.48      0.55        62
         red       0.64      0.89      0.74        63
      yellow       0.57      0.62      0.60        64

    accuracy                           0.67       260
   macro avg       0.68      0.67      0.67       260
weighted avg       0.69      0.67      0.67       260

In [108]:
svm_x_train,svm_x_test,svm_y_train,svm_y_test = train_test_split(x,y,test_size = 0.2 , random_state=83)
svm_model.fit(svm_x_train,svm_y_train)
svm_pred = svm_model.predict(svm_x_test)
print(classification_report(svm_y_test,svm_pred))

              precision    recall  f1-score   support

       green       0.65      0.52      0.58        71
      orange       0.48      0.54      0.51        61
         red       0.60      0.79      0.68        70
      yellow       0.42      0.31      0.36        58

    accuracy                           0.55       260
   macro avg       0.54      0.54      0.53       260
weighted avg       0.55      0.55      0.54       260

In [44]:
df[df['alert']=='red']

      magnitude  depth  cdi  mmi   sig alert
25         7.30   41.0  9.0  8.0  93.0   red
44         7.00   20.0  8.0  8.0 -56.0   red
49         7.20   10.0  9.0  8.0  27.0   red
154        7.50   20.0  8.0  8.0 -22.0   red
185        7.30   19.0  8.0  9.0 -26.0   red
...         ...    ...  ...  ...   ...   ...
1026       7.35   18.0  8.0  8.0 -14.0   red
1027       7.16    9.0  9.0  9.0  79.0   red
1028       7.20    9.0  9.0  8.0  74.0   red
1029       7.20   10.0  9.0  8.0  26.0   red
1030       7.15   20.0  8.0  8.0 -45.0   red

[325 rows x 6 columns]

In [109]:
# from sklearn.metrics import accuracy_score
# for i in range(1,101):
#     x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=i)
#     svm_model.fit(x_train,y_train)
#     svm_pred=svm_model.predict(x_test)
#     b =[]
#     b.append({accuracy_score(y_test,svm_pred)})
#     print(f'for random state : {i} and ACCU in {accuracy_score(y_test,svm_pred)}')